# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024 Intel Corporation. All rights reserved.

# make -f Makefile.so

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../spdk)
include $(SPDK_ROOT_DIR)/mk/spdk.common.mk

SO_VER := 1
SO_MINOR := 0

C_SRCS = zvfs.c
LIBNAME = zvfs

SPDK_MAP_FILE = $(abspath $(CURDIR)/spdk_zvfs.map)

include $(SPDK_ROOT_DIR)/mk/spdk.lib.mk